In [1]:
import pandas as pd
import time

In [2]:
#Time testing for comparison with our big Data
start_time = time.time()
Mental_Health_Dataset = pd.read_csv('Mental Health Dataset.csv')
Mental_Health_Dataset.head()

#Checking the time taken
end_time = time.time()

# Calculating the elapsed time
elapsed_time = end_time - start_time
print(f"\nTime taken: {elapsed_time:.4f} seconds")

Time taken: 0.7673 seconds

In [4]:
#Loading and displaying the dataset
Mental_Health_Dataset = pd.read_csv('Mental Health Dataset.csv')
Mental_Health_Dataset.head()

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
0,8/27/2014 11:29,Female,United States,Corporate,NaN,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,8/27/2014 11:31,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,8/27/2014 11:32,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
3,8/27/2014 11:37,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Yes
4,8/27/2014 11:43,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes

In [4]:
#Check the size of the dataset
#timing
start_time = time.time()

print(f'The dataset has {Mental_Health_Dataset.shape[0]} data objects')

#Checking the time taken
end_time = time.time()

# Calculate elapsed time
elapsed_time = end_time - start_time
print(f"\nTime taken: {elapsed_time:.4f} seconds")

The dataset has 292364 data objects

Time taken: 0.0000 seconds

In [5]:
# Since the dataset is large, we want to focus on UK Health dataset Only
#timing
start_time = time.time()
#Get UK data only
UK_Mental_Health = Mental_Health_Dataset[Mental_Health_Dataset['Country']=='United Kingdom']

#Checking the time taken
end_time = time.time()

# Calculate elapsed time
elapsed_time = end_time - start_time
print(f"\nTime taken: {elapsed_time:.4f} seconds")

Time taken: 0.0650 seconds

In [8]:
UK_Mental_Health.head()

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
15,8/27/2014 12:51,Female,United Kingdom,Corporate,No,No,No,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,No
22,8/27/2014 13:47,Female,United Kingdom,Corporate,No,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
40,8/27/2014 16:14,Female,United Kingdom,Corporate,No,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
41,8/27/2014 16:19,Female,United Kingdom,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Not sure
62,8/28/2014 2:32,Female,United Kingdom,Corporate,No,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No

In [6]:
print(f'The new dataset has {UK_Mental_Health.shape[0]} rows')

The new dataset has 51404 rows

In [7]:
# Starting with data cleaning; Checking for Null values, duplicates and Outliers

#Null check
Null_check = UK_Mental_Health.isnull().values.any()

if Null_check:
    print("There are Null values in the dataset.")
else:
    print("There are no Null values in the dataset.")

UK_Mental_Health.isnull().sum()

There are Null values in the dataset.

Timestamp                    0
Gender                       0
Country                      0
Occupation                   0
self_employed              780
family_history               0
treatment                    0
Days_Indoors                 0
Growing_Stress               0
Changes_Habits               0
Mental_Health_History        0
Mood_Swings                  0
Coping_Struggles             0
Work_Interest                0
Social_Weakness              0
mental_health_interview      0
care_options                 0
dtype: int64

In [10]:
#Percentage Check of null
Null_Percent = (UK_Mental_Health['self_employed'].isnull().sum()/UK_Mental_Health.shape[0])*100
print(f'The null percentage is {Null_Percent:.3f} %')

The null percentage is 1.517 %

In [11]:
#Since the null percentage is 1.54%, it is small meaning, removing them will not have a big impact on the data
UK_Mental_Health_NoNull = UK_Mental_Health.dropna()
null_check = UK_Mental_Health_NoNull.isnull().values.any()

if null_check:
    print("There are Null values in the dataset.")
else:
    print("There are no Null values in the dataset.")

There are no Null values in the dataset.

In [12]:
# Check for duplicates in rows
Duplicates = UK_Mental_Health_NoNull.duplicated().sum()

if Duplicates:
    print("There are duplicate rows in the dataset.")
else:
    print("There are no duplicate rows in the dataset.")

print(f'\nThe Total Number of duplicates are {Duplicates}')

There are duplicate rows in the dataset.

The Total Number of duplicates are 48

In [13]:
#Specific rows with duplicates
UK_Mental_Health_NoNull.loc[UK_Mental_Health_NoNull.duplicated(),:]

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
18286,8/27/2014 12:51,Female,United Kingdom,Corporate,No,No,No,31-60 days,No,No,Maybe,High,No,No,Maybe,Maybe,No
18293,8/27/2014 13:47,Female,United Kingdom,Corporate,No,No,Yes,31-60 days,No,No,Maybe,High,No,No,Maybe,No,Not sure
18311,8/27/2014 16:14,Female,United Kingdom,Corporate,No,No,Yes,31-60 days,No,No,Maybe,High,No,No,Maybe,No,Yes
18312,8/27/2014 16:19,Female,United Kingdom,Corporate,No,Yes,Yes,31-60 days,No,No,Maybe,High,No,No,Maybe,Maybe,Not sure
18333,8/28/2014 2:32,Female,United Kingdom,Corporate,No,No,Yes,31-60 days,No,No,Maybe,High,No,No,Maybe,No,No
18338,8/28/2014 9:16,Female,United Kingdom,Corporate,No,No,No,31-60 days,No,No,Maybe,High,No,No,Maybe,No,No
18346,8/28/2014 12:12,Female,United Kingdom,Corporate,No,No,No,31-60 days,No,No,Maybe,High,No,No,Maybe,Maybe,No
18354,8/28/2014 17:12,Female,United Kingdom,Corporate,No,Yes,Yes,31-60 days,No,No,Maybe,High,No,No,Maybe,No,No
18355,8/28/2014 17:20,Female,United Kingdom,Corporate,No,Yes,No,31-60 days,No,No,Maybe,High,No,No,Maybe,No,No
18356,8/28/2014 18:21,Female,United Kingdom,Corporate,No,Yes,Yes,31-60 days,No,No,Maybe,High,No,No,Maybe,No,No
18359,8/29/2014 5:57,Female,United Kingdom,Corporate,Yes,Yes,Yes,31-60 days,No,No,Maybe,High,No,No,Maybe,No,No
18361,8/29/2014 9:02,Female,United Kingdom,Corporate,No,Yes,No,31-60 days,No,No,Maybe,High,No,No,Maybe,No,Not sure
18379,8/30/2014 19:56,Female,United Kingdom,Corporate,No,No,Yes,31-60 days,No,No,Maybe,High,No,No,Maybe,No,Not sure
18380,9/2/2014 8:24,Female,United Kingdom,Corporate,No,Yes,No,31-60 days,No,No,Maybe,High,No,No,Maybe,Maybe,Yes
18388,2/21/2015 9:18,Female,United Kingdom,Corporate,No,No,Yes,31-60 days,No,No,Maybe,High,No,No,Maybe,No,Yes
18390,2/24/2015 8:54,Female,United Kingdom,Corporate,No,Yes,Yes,31-60 days,No,No,Maybe,High,No,No,Maybe,Maybe,Yes
19859,8/27/2014 12:51,Female,United Kingdom,Others,No,No,No,31-60 days,Yes,Maybe,Yes,High,Yes,Yes,No,Maybe,No
19866,8/27/2014 13:47,Female,United Kingdom,Others,No,No,Yes,31-60 days,Yes,Maybe,Yes,High,Yes,Yes,No,No,Not sure
19884,8/27/2014 16:14,Female,United Kingdom,Others,No,No,Yes,31-60 days,Yes,Maybe,Yes,High,Yes,Yes,No,No,Yes
19885,8/27/2014 16:19,Female,United Kingdom,Others,No,Yes,Yes,31-60 days,Yes,Maybe,Yes,High,Yes,Yes,No,Maybe,Not sure
19906,8/28/2014 2:32,Female,United Kingdom,Others,No,No,Yes,31-60 days,Yes,Maybe,Yes,High,Yes,Yes,No,No,No
19911,8/28/2014 9:16,Female,United Kingdom,Others,No,No,No,31-60 days,Yes,Maybe,Yes,High,Yes,Yes,No,No,No
19919,8/28/2014 12:12,Female,United Kingdom,Others,No,No,No,31-60 days,Yes,Maybe,Yes,High,Yes,Yes,No,Maybe,No
19927,8/28/2014 17:12,Female,United Kingdom,Others,No,Yes,Yes,31-60 days,Yes,Maybe,Yes,High,Yes,Yes,No,No,No
19928,8/28/2014 17:20,Female,United Kingdom,Others,No,Yes,No,31-60 days,Yes,Maybe,Yes,High,Yes,Yes,No,No,No
19929,8/28/2014 18:21,Female,United Kingdom,Others,No,Yes,Yes,31-60 days,Yes,Maybe,Yes,High,Yes,Yes,No,No,No
19932,8/29/2014 5:57,Female,United Kingdom,Others,Yes,Yes,Yes,31-60 days,Yes,Maybe,Yes,High,Yes,Yes,No,No,No
19934,8/29/2014 9:02,Female,United Kingdom,Others,No,Yes,No,31-60 days,Yes,Maybe,Yes,High,Yes,Yes,No,No,Not sure
19952,8/30/2014 19:56,Female,United Kingdom,Others,No,No,Yes,31-60 days,Yes,Maybe,Yes,High,Yes,Yes,No,No,Not sure
19953,9/2/2014 8:24,Female,United Kingdom,Others,No,Yes,No,31-60 days,Yes,Maybe,Yes,High,Yes,Yes,No,Maybe,Yes
19961,2/21/2015 9:18,Female,United Kingdom,Others,No,No,Yes,31-60 days,Yes,Maybe,Yes,High,Yes,Yes,No,No,Yes
19963,2/24/2015 8:54,Female,United Kingdom,Others,No,Yes,Yes,31-60 days,Yes,Maybe,Yes,High,Yes,Yes,No,Maybe,Yes
51803,8/27/2014 12:51,Female,United Kingdom,Student,No,No,No,More than 2 months,Yes,Maybe,Maybe,High,No,Maybe,No,Maybe,No
51810,8/27/2014 13:47,Female,United Kingdom,Student,No,No,Yes,More than 2 months,Yes,Maybe,Maybe,High,No,Maybe,No,No,Not sure
51828,8/27/2014 16:14,Female,United Kingdom,Student,No,No,Yes,More than 2 months,Yes,Maybe,Maybe,High,No,Maybe,No,No,Yes
51829,8/27/2014 16:19,Female,United Kingdom,Student,No,Yes,Yes,More than 2 months,Yes,Maybe,Maybe,High,No,Maybe,No,Maybe,Not sure
51850,8/28/2014 2:32,Female,United Kingdom,Student,No,No,Yes,More than 2 months,Yes,Maybe,Maybe,High,No,Maybe,No,No,No
51855,8/28/2014 9:16,Female,United Kingdom,Student,No,No,No,More than 2 months,Yes,Maybe,Maybe,High,No,Maybe,No,No,No
51863,8/28/2014 12:12,Female,United Kingdom,Student,No,No,No,More than 2 months,Yes,Maybe,Maybe,High,No,Maybe,No,Maybe,No
51871,8/28/2014 17:12,Female,United Kingdom,Student,No,Yes,Yes,More than 2 months,Yes,Maybe,Maybe,High,No,Maybe,No,No,No
51872,8/28/2014 17:20,Female,United Kingdom,Student,No,Yes,No,More than 2 months,Yes,Maybe,Maybe,High,No,Maybe,No,No,No
51873,8/28/2014 18:21,Female,United Kingdom,Student,No,Yes,Yes,More than 2 months,Yes,Maybe,Maybe,High,No,Maybe,No,No,No
51876,8/29/2014 5:57,Female,United Kingdom,Student,Yes,Yes,Yes,More than 2 months,Yes,Maybe,Maybe,High,No,Maybe,No,No,No
51878,8/29/2014 9:02,Female,United Kingdom,Student,No,Yes,No,More than 2 months,Yes,Maybe,Maybe,High,No,Maybe,No,No,Not sure
51896,8/30/2014 19:56,Female,United Kingdom,Student,No,No,Yes,More than 2 months,Yes,Maybe,Maybe,High,No,Maybe,No,No,Not sure
51897,9/2/2014 8:24,Female,United Kingdom,Student,No,Yes,No,More than 2 months,Yes,Maybe,Maybe,High,No,Maybe,No,Maybe,Yes
51905,2/21/2015 9:18,Female,United Kingdom,Student,No,No,Yes,More than 2 months,Yes,Maybe,Maybe,High,No,Maybe,No,No,Yes
51907,2/24/2015 8:54,Female,United Kingdom,Student,No,Yes,Yes,More than 2 months,Yes,Maybe,Maybe,High,No,Maybe,No,Maybe,Yes

In [14]:
# Percentage of Duplicated rows
total_rows = UK_Mental_Health_NoNull.shape[0]
Percent_duplicated = (UK_Mental_Health_NoNull.duplicated().sum()/total_rows)*100
print(f'The percentage of duplicated rows is: {Percent_duplicated:.2f}%')

The percentage of duplicated rows is: 0.09%

In [15]:
# We drop the duplicates
Non_duplicated_data = UK_Mental_Health_NoNull.drop_duplicates()
Duplicates = Non_duplicated_data.duplicated().sum()
if Duplicates:
    print("There are duplicate rows in the dataset.")
else:
    print("There are no duplicate rows in the dataset.")

print(f'\nThe Total Number of duplicates are {Duplicates}')

print(f'\nTotal number of rows in our dataset is: {Non_duplicated_data.shape[0]}')

There are no duplicate rows in the dataset.

The Total Number of duplicates are 0

Total number of rows in our dataset is: 50576

In [16]:
# we remove the Timestamp column given we will not use it for the analysis
Non_duplicated_data.drop('Timestamp', axis =1, inplace=True)
Non_duplicated_data.head()

C:\Users\HomePC\AppData\Local\Temp\ipykernel_13388\3459780420.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Non_duplicated_data.drop('Timestamp', axis =1, inplace=True)

,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
15,Female,United Kingdom,Corporate,No,No,No,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,No
22,Female,United Kingdom,Corporate,No,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
40,Female,United Kingdom,Corporate,No,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
41,Female,United Kingdom,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Not sure
62,Female,United Kingdom,Corporate,No,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No

In [17]:
Cleaned_UK_Mental_Health = Non_duplicated_data
Cleaned_UK_Mental_Health.head()

,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
15,Female,United Kingdom,Corporate,No,No,No,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,No
22,Female,United Kingdom,Corporate,No,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
40,Female,United Kingdom,Corporate,No,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
41,Female,United Kingdom,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Not sure
62,Female,United Kingdom,Corporate,No,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No

In [18]:
Total_rows = Cleaned_UK_Mental_Health.shape[0]
Total_columns = Cleaned_UK_Mental_Health.shape[1]
print(f'The dataset has {Total_rows} rows and {Total_columns} columns')

The dataset has 50576 rows and 16 columns

In [19]:
# Our new Dataset is; we write that back to CSV for further Analysis

Cleaned_UK_Mental_Health.to_csv('Cleaned_UK_Mental_Health.csv', index=False)